language: node_js
node_js:
  - "6"
install:
  - npm install -g firebase-tools
notifications:
  email: false
after_success:
  - npm run build && firebase deploy --token ${FIREBASE_TOKEN} --non-interactive